/**
 * Renders fleet/RUNTIME.md from fleet/runtime-baseline.json.
 *
 * Generated, not written, for the same reason the other reports are: numbers typed by hand drift
 * from the run that produced them and drift silently.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(ROOT, 'fleet/runtime-baseline.json');
if (!fs.existsSync(src)) { console.error('run fleet/sweep-runtime.mjs first'); process.exit(2); }
const { node, results } = JSON.parse(fs.readFileSync(src, 'utf8'));

const audited = results.filter((r) => r.status === 'audited');
const byStatus = {};
for (const r of results) (byStatus[r.status] ??= []).push(r);

const sum = (k) => audited.reduce((a, r) => a + (r[k] || 0), 0);
const responded = sum('probed') ? Math.round((1 - sum('inert') / sum('probed')) * 100) : null;

const L = [];
L.push('# Fleet baseline — runtime');
L.push('');
L.push(`Generated by \`fleet/report-runtime.mjs\` from \`fleet/sweep-runtime.mjs\`. Node ${node}.`);
L.push('');
L.push(`**${audited.length} of ${results.length} sites audited in a browser.** Everything below was`);
L.push('measured by loading pages and clicking, not by reading source.');
L.push('');
L.push('| measure | total | meaning |');
L.push('|---|---:|---|');
L.push(`| routes reached | ${sum('routes')} | discovered by following in-app links |`);
L.push(`| crashed or threw | ${sum('crashed')} | an error boundary rendered, or an uncaught error |`);
L.push(`| routes with no \`<h1>\` | ${sum('untitled')} | no page title in the route's default state |`);
L.push(`| dead-end lists | ${sum('deadEnds')} | a populated table whose rows link nowhere |`);
L.push(`| unmarked tab groups | ${sum('unmarkedTabs')} | the active tab is invisible to the accessibility tree |`);
L.push(`| inert controls | ${sum('inert')} of ${sum('probed')} clicked | ${responded === null ? '—' : `${responded}% responded`} |`);
L.push('');
L.push('A toast is not counted as a response: a handler whose only effect is a success message is');
L.push('the defect, not the reaction to it.');
const noLinks = audited.filter((r) => r.noInAppLinks);
if (noLinks.length) {
  L.push('');
  L.push(`**${noLinks.length} site(s) expose no in-app links at all** — navigation is entirely click`);
  L.push('handlers on buttons. An agent reading the accessibility tree cannot discover their routes,');
  L.push('deep-link into one, or open one in a new tab. It also means this crawl, which follows');
  L.push('links, saw only their entry page: their route counts below are a floor, not a census.');
  L.push('');
  L.push(noLinks.map((r) => `\`${r.site}\``).join(', ') + '.');
}
L.push('');
L.push('## Per site');
L.push('');
L.push('| site | routes | crashed | no title | dead ends | unmarked tabs | inert / clicked |');
L.push('|---|---:|---:|---:|---:|---:|---:|');
for (const r of [...audited].sort((a, b) => (b.inert || 0) - (a.inert || 0) || (b.untitled || 0) - (a.untitled || 0))) {
  L.push(`| ${r.site} | ${r.routes ?? '—'} | ${r.crashed ?? '—'} | ${r.untitled ?? '—'} | ${r.deadEnds ?? '—'} | ${r.unmarkedTabs ?? '—'} | ${r.inert ?? '—'} / ${r.probed ?? '—'} |`);
}
L.push('');
for (const [status, rows] of Object.entries(byStatus)) {
  if (status === 'audited') continue;
  L.push(`## ${status} (${rows.length})`);
  L.push('');
  if (status === 'skipped') {
    L.push('No `node_modules`. Run `node fleet/sweep-runtime.mjs --install` to include these — it is');
    L.push('slow, and installing ~90 Vite apps needs disk and time, which is why layer 2 has been');
    L.push('the thin one.');
    L.push('');
    L.push(rows.map((r) => r.site).join(', ') + '.');
  } else {
    for (const r of rows) L.push(`- \`${r.site}\` — ${r.why || ''}`);
  }
  L.push('');
}
fs.writeFileSync(path.join(ROOT, 'fleet/RUNTIME.md'), L.join('\n'));
console.log(`fleet/RUNTIME.md written — ${audited.length} audited`);
